### ISSUE TITLE
Unable to receive forwarded e-mails when Proton address is used

### ISSUE THREAD

**Issue by x80486** [eegeeZA/spamgourmet-clone#61]
I have a `Proton` e-mail address associated within the `Spamgourmet` account. As soon as it's set, I do not receive the forwarded e-mails anymore, though the web interface correctly accounts for the number of messages forwarded/discarded.

If I change the address to any of the other providers I use, the e-mails are correctly forwarded.

Could it be that there is something configured in `Spamgourmet` that prevents it from forwarding correctly to `Proton` addresses?

I started a thread with their support team, but they are telling me everything is fine on their end, and would need some more information to debug — `SMTP` response and `Message-ID`. I would imagine to orchestrate such thing would take weeks with me in between, so I decided to file the issue here and see initially if somehow you have some setting(s) preventing this, a misconfiguration, or some compatibility problem with their servers.

**Comment by x80486** [comment]
`Proton` folks finally debugged this. They created a `Spamgourmet` account and tried to establish the subscription but the e-mail was never sent/acknowledged, so `Spamgourmet` is somehow malfunctioning with `Proton` — and probably some other e-mail providers as well.

You should take a look at this.

**Comment by josiah-hamilton** [comment]
@x80486 
Thanks for letting us know. I can take a look at replicating the issue this weekend, if it's related to another problem we're having. Did they happen to share any logs of what they encountered? Have Proton implemented a  permanent workaround for receiving mail for spamgourmet, which would be why you closed the issue?

**Comment by x80486** [comment]
They told me `Spamgourmet` never sent the e-mail after they registered an account, so their server logs showed that the `Spamgourmet` confirmation/verification e-mail never reached the mail server(s) — but not, no logs were shared.

Moreover, in the past `30` days, no `Spamgourmet` e-mails were rejected due to their ban list — only 0.1% of `Spamgourmet` e-mails are rejected due to spam content.

I don't think they could implement anything for now, because somehow the e-mails are not reaching their email servers. I'm just using another account to receive the `Spamgourmet` e-mails instead.
